import { RealityConfig } from '../types';

const day = 86400000;
const now = Date.now();
const TAU = Math.PI * 2;

export const parallelRealities: RealityConfig[] = [
  {
    id: 'aetheria-cloud',
    name: 'Aetheria Cloud Matrix',
    codeName: 'REALITY-09 // SIG-Iota',
    spectral: 'White Dwarf Stellar Pair',
    description: 'Floating floating island worlds adrift inside endless shimmering gas clouds.',
    bubblePos: [-28000, -18000, -12000],
    bubbleSize: 6700,
    colorA: '#38bdf8',
    colorB: '#a855f7',
    starColor: '#e0f2fe',
    bodies: [
      { id: 'aeth-star', name: 'AETHER CORE', kind: 'star', meaning: null, note: 'White dwarf star radiating pale violet brilliance.', createdAt: now - 900 * day, radius: 5.5, palette: { deep: '#1e1b4b', base: '#6366f1', high: '#e0e7ff', atmo: '#a5b4fc', ice: '#ffffff' }, orbit: { a: 0, speed: 0, phase: 0, incl: 0 } },
      { id: 'aeth-stratos', name: 'Stratos', kind: 'planet', meaning: 'dream', note: 'Gaseous world with floating coral cities in upper atmosphere.', createdAt: now - 800 * day, radius: 2.2, clouds: true, palette: { deep: '#0c4a6e', base: '#0284c7', high: '#e0f2fe', atmo: '#38bdf8', ice: '#f0f9ff' }, orbit: { a: 35, speed: TAU / 260, phase: 1.1, incl: 0.05 } },
    ],
    entries: [
      { id: 'e-aeth-1', planetId: 'aeth-stratos', title: 'Cities in the Atmosphere', body: 'Spanning thousands of miles above liquid hydrogen cores.', tags: ['sky', 'clouds'], bookmarked: true, archived: false, createdAt: now - 600 * day, updatedAt: now - 600 * day, attachments: [] },
    ],
  },
  {
    id: 'nebulus-veil',
    name: 'Nebulus Veil Void',
    codeName: 'REALITY-10 // SIG-Kappa',
    spectral: 'Dark Wolf-Rayet Star',
    description: 'A universe shrouded in cosmic dust filaments and dark matter tendrils.',
    bubblePos: [28000, 20000, 14000],
    bubbleSize: 7300,
    colorA: '#ec4899',
    colorB: '#6366f1',
    starColor: '#f472b6',
    bodies: [
      { id: 'neb-star', name: 'NEBULUS CORE', kind: 'star', meaning: null, note: 'Wolf-Rayet supergiant shedding heavy stellar winds.', createdAt: now - 920 * day, radius: 6.7, palette: { deep: '#831843', base: '#db2777', high: '#fce7f3', atmo: '#f472b6', ice: '#ffffff' }, orbit: { a: 0, speed: 0, phase: 0, incl: 0 } },
    ],
    entries: [],
  },
  {
    id: 'astral-nexus',
    name: 'Astral Nexus Web',
    codeName: 'REALITY-11 // SIG-Lambda',
    spectral: 'Tri-Star System',
    description: 'Three suns interweaving magnetic orbits in a trinary gravitational balance.',
    bubblePos: [5000, 28000, -20000],
    bubbleSize: 7500,
    colorA: '#f59e0b',
    colorB: '#10b981',
    starColor: '#fbbf24',
    bodies: [
      { id: 'ast-star', name: 'TRINITY CORE', kind: 'star', meaning: null, note: 'Trinary star system locked in chaotic golden orbits.', createdAt: now - 930 * day, radius: 6.3, palette: { deep: '#78350f', base: '#d97706', high: '#fef3c7', atmo: '#fbbf24', ice: '#ffffff' }, orbit: { a: 0, speed: 0, phase: 0, incl: 0 } },
    ],
    entries: [],
  },
  {
    id: 'solaria-radiant',
    name: 'Solaria Radiant Continuum',
    codeName: 'REALITY-12 // SIG-Mu',
    spectral: 'Superluminous Yellow Giant',
    description: 'A golden universe drenched in perpetual stellar illumination.',
    bubblePos: [-15000, -28000, 22000],
    bubbleSize: 7000,
    colorA: '#fbbf24',
    colorB: '#ef4444',
    starColor: '#fef08a',
    bodies: [
      { id: 'solr-star', name: 'SOLARIA MAGNA', kind: 'star', meaning: null, note: 'Blinding golden giant star.', createdAt: now - 960 * day, radius: 7.0, palette: { deep: '#713f12', base: '#eab308', high: '#fef9c3', atmo: '#fde047', ice: '#ffffff' }, orbit: { a: 0, speed: 0, phase: 0, incl: 0 } },
    ],
    entries: [],
  },
  {
    id: 'obsidian-horizon',
    name: 'Obsidian Horizon Deep',
    codeName: 'REALITY-13 // SIG-Nu',
    spectral: 'Neutron Core Star',
    description: 'A dense gravitational realm of black crystal surfaces and intense magnetar field lines.',
    bubblePos: [20000, 14000, -28000],
    bubbleSize: 6900,
    colorA: '#475569',
    colorB: '#0f172a',
    starColor: '#94a3b8',
    bodies: [
      { id: 'obs-star', name: 'OBSIDIAN CORE', kind: 'star', meaning: null, note: 'Ultra-dense neutron star.', createdAt: now - 970 * day, radius: 5.2, palette: { deep: '#0f172a', base: '#334155', high: '#f1f5f9', atmo: '#64748b', ice: '#ffffff' }, orbit: { a: 0, speed: 0, phase: 0, incl: 0 } },
    ],
    entries: [],
  },
  {
    id: 'zenith-quantum',
    name: 'Zenith Quantum Realm',
    codeName: 'REALITY-14 // SIG-Xi',
    spectral: 'Quantum Tachyonic Singularity',
    description: 'A universe where matter oscillates between particle waves and light structures.',
    bubblePos: [-22000, 24000, -16000],
    bubbleSize: 7100,
    colorA: '#06b6d4',
    colorB: '#a855f7',
    starColor: '#67e8f9',
    bodies: [
      { id: 'zen-star', name: 'ZENITH CORE', kind: 'star', meaning: null, note: 'Quantum tachyonic star.', createdAt: now - 910 * day, radius: 6.1, palette: { deep: '#155e75', base: '#0891b2', high: '#cff4fc', atmo: '#22d3ee', ice: '#ffffff' }, orbit: { a: 0, speed: 0, phase: 0, incl: 0 } },
    ],
    entries: [],
  },
  {
    id: 'quantum-foam',
    name: 'Quantum Foam Sub-Space',
    codeName: 'REALITY-15 // SIG-Omicron',
    spectral: 'Planck Density Foam',
    description: 'The micro-dimensional foam universe where wormholes spawn and dissolve instantly.',
    bubblePos: [32000, -8000, 10000],
    bubbleSize: 6800,
    colorA: '#8b5cf6',
    colorB: '#ec4899',
    starColor: '#ddd6fe',
    bodies: [
      { id: 'qf-star', name: 'PLANCK CORE', kind: 'star', meaning: null, note: 'Quantum foam core star.', createdAt: now - 945 * day, radius: 5.6, palette: { deep: '#4c1d95', base: '#7c3aed', high: '#f5f3ff', atmo: '#c4b5fd', ice: '#ffffff' }, orbit: { a: 0, speed: 0, phase: 0, incl: 0 } },
    ],
    entries: [],
  },
  {
    id: 'elysium-prism',
    name: 'Elysium Prism Matrix',
    codeName: 'REALITY-16 // SIG-Pi',
    spectral: 'Crystalline Prism Star',
    description: 'Refracts light into rainbows of primary spectra across all planetary orbits.',
    bubblePos: [-10000, -32000, -18000],
    bubbleSize: 7400,
    colorA: '#f43f5e',
    colorB: '#3b82f6',
    starColor: '#fda4af',
    bodies: [
      { id: 'ely-star', name: 'PRISM CORE', kind: 'star', meaning: null, note: 'Multichromatic crystal sun.', createdAt: now - 925 * day, radius: 6.3, palette: { deep: '#881337', base: '#e11d48', high: '#ffe4e6', atmo: '#fb7185', ice: '#ffffff' }, orbit: { a: 0, speed: 0, phase: 0, incl: 0 } },
    ],
    entries: [],
  },
  {
    id: 'draco-abyssal',
    name: 'Draco Abyssal Sector',
    codeName: 'REALITY-17 // SIG-Rho',
    spectral: 'Deep Void Black Star',
    description: 'An ancient, quiet galaxy located in the deepest cosmic void gulfs.',
    bubblePos: [12000, 32000, 24000],
    bubbleSize: 7200,
    colorA: '#1e293b',
    colorB: '#475569',
    starColor: '#cbd5e1',
    bodies: [
      { id: 'dra-star', name: 'DRACO CORE', kind: 'star', meaning: null, note: 'Dim gray dwarf star.', createdAt: now - 985 * day, radius: 5.0, palette: { deep: '#020617', base: '#1e293b', high: '#f8fafc', atmo: '#475569', ice: '#ffffff' }, orbit: { a: 0, speed: 0, phase: 0, incl: 0 } },
    ],
    entries: [],
  },
  {
    id: 'umbra-shadow',
    name: 'Umbra Shadow Dimension',
    codeName: 'REALITY-18 // SIG-Sigma',
    spectral: 'Anti-Matter Radiant Core',
    description: 'A dark inverted universe where light creates shadows and darkness glows softly.',
    bubblePos: [-32000, 8000, 26000],
    bubbleSize: 7000,
    colorA: '#18181b',
    colorB: '#71717a',
    starColor: '#a1a1aa',
    bodies: [
      { id: 'umb-star', name: 'UMBRA CORE', kind: 'star', meaning: null, note: 'Anti-matter core star.', createdAt: now - 915 * day, radius: 5.9, palette: { deep: '#09090b', base: '#27272a', high: '#fafafa', atmo: '#71717a', ice: '#ffffff' }, orbit: { a: 0, speed: 0, phase: 0, incl: 0 } },
    ],
    entries: [],
  },
  {
    id: 'andromeda-echo',
    name: 'Andromeda Echo Horizon',
    codeName: 'REALITY-19 // SIG-Tau',
    spectral: 'Spiral Arm Core Giant',
    description: 'An expansive spiral galaxy realm with giant blue arm structures.',
    bubblePos: [26000, -24000, -22000],
    bubbleSize: 7300,
    colorA: '#0284c7',
    colorB: '#38bdf8',
    starColor: '#7dd3fc',
    bodies: [
      { id: 'and-star', name: 'ANDROMEDA CORE', kind: 'star', meaning: null, note: 'Galactic bulge giant star.', createdAt: now - 955 * day, radius: 6.6, palette: { deep: '#0369a1', base: '#0284c7', high: '#f0f9ff', atmo: '#38bdf8', ice: '#ffffff' }, orbit: { a: 0, speed: 0, phase: 0, incl: 0 } },
    ],
    entries: [],
  },
  {
    id: 'orion-nursery',
    name: 'Orion Nursery Matrix',
    codeName: 'REALITY-20 // SIG-Upsilon',
    spectral: 'Stellar Nursery Cluster',
    description: 'A newborn universe filled with glowing stellar protostars and colorful gas nebulae.',
    bubblePos: [-18000, -22000, -28000],
    bubbleSize: 7500,
    colorA: '#f43f5e',
    colorB: '#fbbf24',
    starColor: '#fecdd3',
    bodies: [
      { id: 'ori-star', name: 'ORION CORE', kind: 'star', meaning: null, note: 'Protostellar nursery cluster core.', createdAt: now - 995 * day, radius: 6.9, palette: { deep: '#9f1239', base: '#e11d48', high: '#fff1f2', atmo: '#fb7185', ice: '#ffffff' }, orbit: { a: 0, speed: 0, phase: 0, incl: 0 } },
    ],
    entries: [],
  },
];
